workspace(name = "build_buildtools_example")

local_repository(
    name = "cgrindel_bazel_starlib",
    path = "../../..",
)

load("@cgrindel_bazel_starlib//:deps.bzl", "bazel_starlib_dependencies")

# Be sure to specify that you do not want to use the prebuilt tools
bazel_starlib_dependencies(
    use_bazeldoc = False,
    use_prebuilt_buildtools = False,
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

# Buildtools Dependencies

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.19.1")

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
