name: Set up caches for Bazel
description: Set up action caches for a workspace's Bazel installations and disk cache.
inputs:
  name:
    description: The name of the repository.
    required: true
runs:
  using: composite
  steps:
    - name: Bazel Repo Cache for ${{ inputs.name }}
      uses: cgrindel/bazel-github-actions/actions/setup_action_cache@main
      with:
        path: ~/.cache/bazel_repo
        cache_name: ${{ inputs.name }}-repo
        key_suffix: ${{ hashFiles('WORKSPACE') }}

    - name: Bazel Disk Cache for ${{ inputs.name }}
      uses: cgrindel/bazel-github-actions/actions/setup_action_cache@main
      with:
        path: ~/.cache/bazel_disk
        cache_name: ${{ inputs.name }}-disk
        key_suffix: ${{ github.sha }}
