name: Set up caches for Bazel
inputs:
  name:
    description: The name of the repository.
    required: true
runs:
  using: composite
  steps:
    - name: Bazel Repo Cache for ${{ inputs.name }}
      uses: ./.github/actions/setup_action_cache
      with:
        path: ~/.cache/bazel_repo
        cache_name: ${{ inputs.name }}-repo
        key_suffix: ${{ hashFiles('WORKSPACE') }}

    - name: Bazel Repo Cache for ${{ inputs.name }}
      uses: ./.github/actions/setup_action_cache
      with:
        path: ~/.cache/bazel_disk
        cache_name: ${{ inputs.name }}-disk
        key_suffix: ${{ github.sha }}
