name: Execute Test
inputs:
  test_target:
    description: The test target to execute.
    required: true
  github_token:
    description: The Github token to authenticate gh CLI.
    required: true
runs:
  using: composite
  steps:
    - name: Execute Test
      shell: bash
      env:
        TEST_TARGET: ${{ inputs.test_target }}
        # The tests make use of Github-specific functionality (e.g. gh).
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        bazelisk test "${TEST_TARGET}"
