workspace(name = "simple_example")

local_repository(
    name = "cgrindel_bazel_starlib",
    path = "../../..",
)

bazel_starlib_dependencies()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
