name: Build and Test

inputs:
  release_tag:
    required: true
    type: string
  readme_path:
    required: true
    type: string
    default: README.md
  update_readme_target:
    required: true
    type: string
    default: "//:update_readme"

runs:
  using: composite
  steps:

    - name: Update README.md
      shell: bash
      env:
        UPDATE_README_TARGET: ${{ inputs.update_readme_target }}
        RELEASE_TAG: ${{ inputs.release_tag }}
        README_PATH: ${{ inputs.readme_path }}
      run: |
        bazelisk run "${UPDATE_README_TARGET}" -- \
          --readme "${README_PATH}"
          "${RELEASE_TAG}"

    - name: Commit Changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: Update README.md for ${{ inputs.release_tag }}
        add: ${{ inputs.readme_path }}
        branch: main
