name: Update README.md, Commit, and Push to Branch

inputs:
  release_tag:
    required: true
    type: string
  github_token:
    description: The Github token to authenticate PR operations.
    required: true
  readme_path:
    required: true
    type: string
    default: README.md
  update_readme_target:
    required: true
    type: string
    default: "//:update_readme"

runs:
  using: composite
  steps:

    - name: Update README.md
      shell: bash
      env:
        UPDATE_README_TARGET: ${{ inputs.update_readme_target }}
        RELEASE_TAG: ${{ inputs.release_tag }}
        README_PATH: ${{ inputs.readme_path }}
      run: |
        bazelisk run "${UPDATE_README_TARGET}" -- \
          --readme "${README_PATH}" \
          "${RELEASE_TAG}"

    - name: Create PR for README.md Update
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.github_token }}
        add-paths: |
          ${{ inputs.readme_path }}
        branch: auto_update_readme_for_${{ inputs.release_tag }}
        base: main
        delete-branch: true
        title: Update REAMDE.md for ${{ inputs.release_tag }}
        body: Automated update of `${{ inputs.readme_path }}` for release ${{ inputs.release_tag }}

    - name: Enable PR Automerge
      if: steps.create_pr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v1
      with:
        token: ${{ inputs.github_token }}
        pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
        merge-method: squash

    # - name: Commit Changes
    #   uses: EndBug/add-and-commit@v7
    #   with:
    #     default_author: github_actions
    #     message: Update README.md for ${{ inputs.release_tag }}
    #     add: ${{ inputs.readme_path }}
    #     branch: auto_update_readme_for_${{ inputs.release_tag }}
    #     branch_mode: create
