name: Configure the Git Repository User

runs:
  using: composite
  steps:
    - name: Configure the Git Repository User
      shell: bash
      run: |
        # Only set the git user if it is not set.
        git_config="$(git config -l)"
        [[ "$git_config" =~ "user.name" ]] && exit 0

        # Ensure that a user is configured
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

