name: Configure bzlmod
inputs:
  enabled:
    description: Boolean value that specifies whether bzlmod should be enabled.
    required: true
runs:
  using: composite
  steps:
    - name: Enable bzmod
      if: inputs.enabled == 'true'
      shell: bash
      run: |
        cat >> "child_workspace.bazelrc" <<EOF
        # bzlmod is always enabled in Bazel 9
        EOF
    - name: Disable bzmod
      if: inputs.enabled != 'true'
      shell: bash
      run: |
        cat >> "child_workspace.bazelrc" <<EOF
        # bzlmod is always enabled in Bazel 9
        EOF
