name: Configure bzlmod

inputs:
  enabled:
    description: Boolean value that specifies whether bzlmod should be enabled.
    required: true

runs:
  using: composite
  steps:
    - name: DEBUG BEFORE
      shell: bash
      run: |
        echo >&2 "BEFORE CONFIGURE"
        pwd >&2
        ls -l >&2
        cat >&2 "shared.bazelrc"
    - name: Enable bzmod
      if: inputs.enabled == 'true'
      shell: bash
      run: |
        cat >> "shared.bazelrc" <<EOF
        # Override earlier settings
        common --enable_bzlmod
        EOF
    - name: Disable bzmod
      if: inputs.enabled != 'true'
      shell: bash
      run: |
        cat >> "shared.bazelrc" <<EOF
        # Override earlier settings
        common --noenable_bzlmod
        EOF
    - name: DEBUG AFTER
      shell: bash
      run: |
        echo >&2 "AFTER CONFIGURE"
        pwd >&2
        cat >&2 "shared.bazelrc"
