name: Set up Bazel for CI
description: Configures Bazel to run with the ci configuration values.
runs:
  using: composite
  steps:
    - name: Write local.bazelrc File
      shell: bash
      run: |
        cat >local.bazelrc <<EOF
        common --config=ci
        EOF

    - name: Output the Bazel Info
      shell: bash
      run: |
        bazelisk info

