name: Update README.md, Commit, and Push to Branch
description: Updates a README.md file for a release, creates a PR and enables automerge for the PR.

inputs:
  release_tag:
    required: true
    type: string
  github_token:
    description: The Github token to authenticate PR operations.
    required: true
  readme_path:
    required: true
    type: string
    default: README.md
  update_readme_target:
    required: true
    type: string
    default: "//release:update_readme"
  base_branch:
    description: The branch being merged to.
    required: true
    type: string
    default: main

runs:
  using: composite
  steps:

    - name: Update README.md
      shell: bash
      env:
        UPDATE_README_TARGET: ${{ inputs.update_readme_target }}
        RELEASE_TAG: ${{ inputs.release_tag }}
        README_PATH: ${{ inputs.readme_path }}
      run: |
        bazelisk run "${UPDATE_README_TARGET}" -- \
          --readme "${README_PATH}" \
          "${RELEASE_TAG}"

    - name: Create PR for README.md Update
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.github_token }}
        add-paths: |
          ${{ inputs.readme_path }}
        branch: auto_update_readme_for_${{ inputs.release_tag }}
        base: ${{ inputs.base_branch }}
        delete-branch: true
        title: Update REAMDE.md for ${{ inputs.release_tag }}
        body: Automated update of `${{ inputs.readme_path }}` for release ${{ inputs.release_tag }}

    - name: Enable PR Automerge
      if: steps.create_pr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v1
      with:
        token: ${{ inputs.github_token }}
        pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
        merge-method: squash
