workspace(name = "markdown_simple_example")

local_repository(
    name = "cgrindel_bazel_starlib",
    path = "../../..",
)

load("@cgrindel_bazel_starlib//:deps.bzl", "bazel_starlib_dependencies")

bazel_starlib_dependencies(use_bazeldoc = False)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

# MARK: - Markdown TOC Deps

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("@cgrindel_bazel_starlib//:go_deps.bzl", "bazel_starlib_go_dependencies")
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

bazel_starlib_go_dependencies()

go_rules_dependencies()

go_register_toolchains(version = "1.19.1")

gazelle_dependencies()
