workspace(name = "markdown_simple_example")

local_repository(
    name = "cgrindel_bazel_starlib",
    path = "../../..",
)

load("@cgrindel_bazel_starlib//:deps.bzl", "bazel_starlib_dependencies")

bazel_starlib_dependencies()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load("@build_bazel_rules_nodejs//:repositories.bzl", "build_bazel_rules_nodejs_dependencies")

build_bazel_rules_nodejs_dependencies()

load("@cgrindel_bazel_starlib//markdown:defs.bzl", "markdown_register_node_deps")

markdown_register_node_deps()
