name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    # NOTE: Need to provide a valid ref (e.g. SHA, release tag, branch). Github is working to add
    # local reference support. (https://github.community/t/ref-head-in-reusable-workflows/203690)
    uses: cgrindel/bazel-starlib/.github/workflows/build_and_test.yml@18f5ae29c570a7c75d022b959de265f07d8c0aa3
