name: Scheduled Builds

on:
  schedule:
    # Every day at 11:13 UTC.
    - cron: '13 11 * * *'

jobs:
  macos_build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: bazel-starlib
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  ubuntu_build:
    runs-on: ubuntu-20.04
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: bazel-starlib
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  all_ci_tests:
    runs-on: ubuntu-20.04
    needs: [macos_build, ubuntu_build]
    steps:
      - name: All is Well
        shell: bash
        run: |
          echo "All is well!"

