name: Test Examples 
description: Execute an example integration test.

inputs:
  github_token:
    description: The Github token to authenticate gh CLI.
    required: true
  example_dir:
    description: The directory under the examples.
    rquired: true
  example_name:
    description: The name of the example.
    required: true
  bazel_version:
    description: The Bazel version suffix (e.g. semver or .bazelversion)
    required: true

runs:
  using: composite
  steps:
    - name: Execute Integration Test
      shell: bash
      env:
        # The integration tests make use of Github-specific functionality 
        # (e.g. gh).
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        bazelisk test //examples/${{ inputs.example_dir }}:${{ inputs.example_name }}_test_bazel_${{ inputs.bazel_version }}

